### PR TITLE
Switch to Mirror Branch action

### LINKED ISSUE #7: Why is `fetch-depth: 0` needed?
I tried setting this up on another repo I have today, and the mirror action failed without `fetch-depth: 0` ([logs](https://github.com/chancancode/ember-concurrency-async/runs/788778347?check_suite_focus=true)). The Git error was:

```
Run git push origin HEAD:master HEAD:main
  git push origin HEAD:master HEAD:main
  shell: /bin/bash -e {0}
To https://github.com/chancancode/ember-concurrency-async
 ! [rejected]        HEAD -> master (fetch first)
error: failed to push some refs to 'https://github.com/chancancode/ember-concurrency-async'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```

Which is similar to what I had encountered in the past. I brought back `fetch-depth: 0` for now since it is better for it to be a bit slow than for others to run into the problem, but I do think we should investigate what's up and whether we can do something a bit more targeted (e.g. fetching a single commit from each branch?).

### PR DESCRIPTION
**Pull request by chancancode**
Fixes #7 

TODOs:

- [x] @chancancode will test this on https://github.com/chancancode/ember-concurrency-async
- [ ] @dscho mind trying this out to see if it works in your setup?

### CODE REVIEW

**Comment by chancancode** [comment]
cc @zofrex

**Comment by dscho** [comment]
Interesting! It uses the GitHub API directly and should therefore be much faster even than a partial clone...

I will test this in my setups as soon as I'm on a computer again, but I don't expect any problems: in my experience, GitHub API calls are very robust.

**Comment by chancancode** [comment]
I tested this on https://github.com/chancancode/ember-concurrency-async and it worked perfectly, I made a small tweak to disable force pushing (it is enabled by default for some reason, but shouldn't be necessary here). As far as I am concerned, this is good to go so @dscho feel free to merge this whenever you have a chance to confirm that it works for you. Thanks @zofrex!

**Review by dscho — APPROVED** [review]
This looks good, and I am convinced that it works correctly (even wïthout testing it manually).

**Comment by zofrex** [comment]
Re: force pushing, I thought this was necessary to achieve "mirroring" in the sense that I personally expect that term to mean.

I am curious to hear why it is not necessary for you, and particularly what you want to happen in the event someone force pushes to your new base branch. You aren't the first person to raise an eyebrow at the default so perhaps it needs a change!

**Comment by dscho** [comment]
> I am curious to hear why it is not necessary for you

I think the idea here is to have bidirectional mirroring between `master` and `main`, in case a developer pushed to `master` by accident. To support that scenario, we're using your Action twice: once in the direction `main` -> `master`, and then in the reverse. Now, if there is no divergence, one of those directions will result in a fast-forward and the other in a no-op.

But what if two developers pushed almost simultaneously to `main` and to `master`? In that case, we do not want one to "win" and the other to (silently!) "lose". After all, the user who pushed the revision that would be overwritten by the Action would have no feedback that their changes were reverted. That's why we don't want to force the push.

**Pull request merged**
